services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.painel.rule=Host(`painel.automacao.fsmhub.net`)"
      - "traefik.http.routers.painel.entrypoints=web"
      - "traefik.http.routers.painel.middlewares=auth-painel@file"
      - "traefik.http.services.painel.loadbalancer.server.port=80"

networks:
  proxy:  # Agora será criada automaticamente como interna
